### PR TITLE
[TASK] Made changes to make Composer work with the latest version

### LINKED ISSUE #3: Can't update to version 1.0.3
**To Reproduce**
1. Go to Magento 2 root folder
2. Run command 'composer require tig/persistent-shopping-cart-magento2:1.0.3'

**Expected result**
Latest update of module is installed.

**Actual result**
Composer returns an error:
'tig/persistent-shopping-cart-magento2 1.0.3 requires tig/core 1.0.* -> no matching package found.'

**Workaround**
None that I know of.

**Please complete the following information**
- Magento version: 2.3.3
- PHP version: 7.2

### PR DESCRIPTION
**Pull request by JKetelaar**
Fixes #3

### CODE REVIEW

**Comment by JKetelaar** [comment]
@tig-dennisvanderhammen @tig-svenluiks

**Comment by tig-dennisvanderhammen** [comment]
Hi @JKetelaar ,

I'm pretty sure version 1.0.3 relies on the tig/core in some way or another. As mentioned in another issue, the tig/core is a deprecated extension of ours.

Because this seems to be causing some issues for the persistent shopping cart, I'm discussing with our team to put the tig/core back online, at least until it is properly removed from the persistent shopping cart extension.

**Comment by JKetelaar** [comment]
Any update on this? I would love to be able to manage the settings for this module from the backend.

**Comment by tig-dennisvanderhammen** [comment]
Hi @JKetelaar ,

Instead, we have decided to put the tig/core extension back for now. You should be able to update to version 1.0.4 now.

**Pull request closed without merging**
